### ISSUE TITLE
C3: JS Error when using mute events

### ISSUE THREAD

**Issue by magalvao** [gameeapp/gamee-js-construct3#1]
When using the Mute conditions for my game in C3, this error happens:

![image](https://user-images.githubusercontent.com/7683867/36159766-b319fe14-10c6-11e8-8aba-6cdaf62ff8d1.png)

I can play the game normally after dismissing the dialog.
The error occurs on C3 preview and on Gamee Emulator.

The events I used:
![image](https://user-images.githubusercontent.com/7683867/36159854-ebcace5a-10c6-11e8-9795-2aa54e230eb3.png)

When I disable those lines, the error don't appears.

**Comment by EntityB** [comment]
Thanks we will fix that. 

Include this in your game. Judges will be notified alert message might appear.

**Comment by EntityB** [comment]
#4
